apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false #nie pushuj do dokerhuba
  artifacts:
    - image: darglk/blog-auth
      context: ../blog-auth
      jib: {
        args: [-DskipTests]
      }
      # docker:
      #   dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/java/**/*.java'
            dest: .