apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false #nie pushuj do dokerhuba
  artifacts:
    - image: darglk/blog-auth
      context: ../blog-auth
      jib: {}
      # docker:
      #   dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/java/**/*.java'
            dest: .